#ifndef PDICCUISEARCH_CHARCODE_H_
#define PDICCUISEARCH_CHARCODE_H_

#define CHARCODE_ASCII     0
#define CHARCODE_LATIN1    1
#define CHARCODE_SHIFTJIS  7
#define CHARCODE_UTF8      8
#define CHARCODE_BOCU1     9

#endif // PDICCUISEARCH_CHARCODE_H_

